//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.03 at 12:58:12 PM EST 
//

package com.safe.hsap.domainobjects.services;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="pId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="passengerFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="passengerLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="passengerGender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="passengerNationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="passengerPassportNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="passengerDob" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="passengerPassportExpiry" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="passengerType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="custId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aptno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="custState" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="zip" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="custEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contactNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="countryCodePhone" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="emergencyContactNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emergencyContactFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="emergencyContactLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customerType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bookingAgentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bookingAgentWebAdd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bookingAgentContactNo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="membershipname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="assoicatedAirline" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="membershipStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="membershipEndtDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "pId", "passengerFirstName", "passengerLastName", "passengerGender",
		"passengerNationality", "passengerPassportNo", "passengerDob", "passengerPassportExpiry", "passengerType",
		"custId", "street", "aptno", "city", "custState", "country", "zip", "custEmail", "contactNum",
		"countryCodePhone", "emergencyContactNum", "emergencyContactFirstName", "emergencyContactLastName",
		"customerType", "bookingAgentName", "bookingAgentWebAdd", "bookingAgentContactNo", "membershipname",
		"assoicatedAirline", "membershipStartDate", "membershipEndtDate" })
@XmlRootElement(name = "customerRegirationUpdate")
public class CustomerRegistrationUpdate {

	@XmlElement(required = true)
	protected int pId;
	@XmlElement(required = true)
	protected String passengerFirstName;
	@XmlElement(required = true)
	protected String passengerLastName;
	@XmlElement(required = true)
	protected String passengerGender;
	@XmlElement(required = true)
	protected String passengerNationality;
	@XmlElement(required = true)
	protected String passengerPassportNo;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected Date passengerDob;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected Date passengerPassportExpiry;
	@XmlElement(required = true)
	protected String passengerType;
	protected int custId;
	@XmlElement(required = true)
	protected String street;
	@XmlElement(required = true)
	protected String aptno;
	@XmlElement(required = true)
	protected String city;
	@XmlElement(required = true)
	protected String custState;
	@XmlElement(required = true)
	protected String country;
	protected int zip;
	@XmlElement(required = true)
	protected String custEmail;
	@XmlElement(required = true)
	protected String contactNum;
	protected int countryCodePhone;
	@XmlElement(required = true)
	protected String emergencyContactNum;
	@XmlElement(required = true)
	protected String emergencyContactFirstName;
	@XmlElement(required = true)
	protected String emergencyContactLastName;
	@XmlElement(required = true)
	protected String customerType;
	@XmlElement(required = true)
	protected String bookingAgentName;
	@XmlElement(required = true)
	protected String bookingAgentWebAdd;
	@XmlElement(required = true)
	protected String bookingAgentContactNo;
	@XmlElement(required = true)
	protected String membershipname;
	@XmlElement(required = true)
	protected String assoicatedAirline;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected Date membershipStartDate;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected Date membershipEndtDate;

	/**
	 * Gets the value of the pId property.
	 * 
	 */
	public int getpId() {
		return pId;
	}

	/**
	 * Sets the value of the pId property.
	 * 
	 */

	public void setpId(int pId) {
		this.pId = pId;
	}

	/**
	 * Gets the value of the passengerFirstName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPassengerFirstName() {
		return passengerFirstName;
	}

	/**
	 * Sets the value of the passengerFirstName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPassengerFirstName(String value) {
		this.passengerFirstName = value;
	}

	/**
	 * Gets the value of the passengerLastName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPassengerLastName() {
		return passengerLastName;
	}

	/**
	 * Sets the value of the passengerLastName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPassengerLastName(String value) {
		this.passengerLastName = value;
	}

	/**
	 * Gets the value of the passengerGender property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPassengerGender() {
		return passengerGender;
	}

	/**
	 * Sets the value of the passengerGender property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPassengerGender(String value) {
		this.passengerGender = value;
	}

	/**
	 * Gets the value of the passengerNationality property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPassengerNationality() {
		return passengerNationality;
	}

	/**
	 * Sets the value of the passengerNationality property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPassengerNationality(String value) {
		this.passengerNationality = value;
	}

	/**
	 * Gets the value of the passengerPassportNo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPassengerPassportNo() {
		return passengerPassportNo;
	}

	/**
	 * Sets the value of the passengerPassportNo property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPassengerPassportNo(String value) {
		this.passengerPassportNo = value;
	}

	/**
	 * Gets the value of the passengerDob property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getPassengerDob() {
		return passengerDob;
	}

	/**
	 * Sets the value of the passengerDob property.
	 * 
	 * @param value allowed object is {@link Date }
	 * 
	 */
	public void setPassengerDob(Date value) {
		this.passengerDob = value;
	}

	/**
	 * Gets the value of the passengerPassportExpiry property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getPassengerPassportExpiry() {
		return passengerPassportExpiry;
	}

	/**
	 * Sets the value of the passengerPassportExpiry property.
	 * 
	 * @param value allowed object is {@link Date }
	 * 
	 */
	public void setPassengerPassportExpiry(Date value) {
		this.passengerPassportExpiry = value;
	}

	/**
	 * Gets the value of the passengerType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPassengerType() {
		return passengerType;
	}

	/**
	 * Sets the value of the passengerType property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPassengerType(String value) {
		this.passengerType = value;
	}

	/**
	 * Gets the value of the custId property.
	 * 
	 */
	public int getCustId() {
		return custId;
	}

	/**
	 * Sets the value of the custId property.
	 * 
	 */
	public void setCustId(int value) {
		this.custId = value;
	}

	/**
	 * Gets the value of the street property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStreet() {
		return street;
	}

	/**
	 * Sets the value of the street property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStreet(String value) {
		this.street = value;
	}

	/**
	 * Gets the value of the aptno property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAptno() {
		return aptno;
	}

	/**
	 * Sets the value of the aptno property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAptno(String value) {
		this.aptno = value;
	}

	/**
	 * Gets the value of the city property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCity() {
		return city;
	}

	/**
	 * Sets the value of the city property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCity(String value) {
		this.city = value;
	}

	/**
	 * Gets the value of the custState property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCustState() {
		return custState;
	}

	/**
	 * Sets the value of the custState property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCustState(String value) {
		this.custState = value;
	}

	/**
	 * Gets the value of the country property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * Sets the value of the country property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCountry(String value) {
		this.country = value;
	}

	/**
	 * Gets the value of the zip property.
	 * 
	 */
	public int getZip() {
		return zip;
	}

	/**
	 * Sets the value of the zip property.
	 * 
	 */
	public void setZip(int value) {
		this.zip = value;
	}

	/**
	 * Gets the value of the custEmail property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCustEmail() {
		return custEmail;
	}

	/**
	 * Sets the value of the custEmail property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCustEmail(String value) {
		this.custEmail = value;
	}

	/**
	 * Gets the value of the contactNum property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContactNum() {
		return contactNum;
	}

	/**
	 * Sets the value of the contactNum property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setContactNum(String value) {
		this.contactNum = value;
	}

	/**
	 * Gets the value of the countryCodePhone property.
	 * 
	 */
	public int getCountryCodePhone() {
		return countryCodePhone;
	}

	/**
	 * Sets the value of the countryCodePhone property.
	 * 
	 */
	public void setCountryCodePhone(int value) {
		this.countryCodePhone = value;
	}

	/**
	 * Gets the value of the emergencyContactNum property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEmergencyContactNum() {
		return emergencyContactNum;
	}

	/**
	 * Sets the value of the emergencyContactNum property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setEmergencyContactNum(String value) {
		this.emergencyContactNum = value;
	}

	/**
	 * Gets the value of the emergencyContactFirstName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEmergencyContactFirstName() {
		return emergencyContactFirstName;
	}

	/**
	 * Sets the value of the emergencyContactFirstName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setEmergencyContactFirstName(String value) {
		this.emergencyContactFirstName = value;
	}

	/**
	 * Gets the value of the emergencyContactLastName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEmergencyContactLastName() {
		return emergencyContactLastName;
	}

	/**
	 * Sets the value of the emergencyContactLastName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setEmergencyContactLastName(String value) {
		this.emergencyContactLastName = value;
	}

	/**
	 * Gets the value of the customerType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCustomerType() {
		return customerType;
	}

	/**
	 * Sets the value of the customerType property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCustomerType(String value) {
		this.customerType = value;
	}

	/**
	 * Gets the value of the bookingAgentName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBookingAgentName() {
		return bookingAgentName;
	}

	/**
	 * Sets the value of the bookingAgentName property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBookingAgentName(String value) {
		this.bookingAgentName = value;
	}

	/**
	 * Gets the value of the bookingAgentWebAdd property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBookingAgentWebAdd() {
		return bookingAgentWebAdd;
	}

	/**
	 * Sets the value of the bookingAgentWebAdd property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBookingAgentWebAdd(String value) {
		this.bookingAgentWebAdd = value;
	}

	/**
	 * Gets the value of the bookingAgentContactNo property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBookingAgentContactNo() {
		return bookingAgentContactNo;
	}

	/**
	 * Sets the value of the bookingAgentContactNo property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBookingAgentContactNo(String value) {
		this.bookingAgentContactNo = value;
	}

	/**
	 * Gets the value of the membershipname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getMembershipname() {
		return membershipname;
	}

	/**
	 * Sets the value of the membershipname property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setMembershipname(String value) {
		this.membershipname = value;
	}

	/**
	 * Gets the value of the assoicatedAirline property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAssoicatedAirline() {
		return assoicatedAirline;
	}

	/**
	 * Sets the value of the assoicatedAirline property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setAssoicatedAirline(String value) {
		this.assoicatedAirline = value;
	}

	/**
	 * Gets the value of the membershipStartDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getMembershipStartDate() {
		return membershipStartDate;
	}

	/**
	 * Sets the value of the membershipStartDate property.
	 * 
	 * @param value allowed object is {@link Date }
	 * 
	 */
	public void setMembershipStartDate(Date value) {
		this.membershipStartDate = value;
	}

	/**
	 * Gets the value of the membershipEndtDate property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getMembershipEndtDate() {
		return membershipEndtDate;
	}

	/**
	 * Sets the value of the membershipEndtDate property.
	 * 
	 * @param value allowed object is {@link Date }
	 * 
	 */
	public void setMembershipEndtDate(Date value) {
		this.membershipEndtDate = value;
	}

}
