//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.09 at 07:31:24 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.safe.com/hsap/domainobjects/services", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.safe.hsap.domainobjects.services;
