//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.12.09 at 07:31:24 PM EST 
//

package com.safe.hsap.domainobjects.services;

import java.util.Date;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="custEmail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mealid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cabinid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="speRequestid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="flDetailid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="planid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cfname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cmname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="clname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardnum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardtype" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardExpiry" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "custEmail", "mealid", "cabinid", "speRequestid", "flDetailid", "planid", "cfname",
		"cmname", "clname", "cardnum", "cardtype", "cardExpiry" })
@XmlRootElement(name = "planTransactionSaveRequest")
public class PlanTransactionSaveRequest {

	@XmlElement(required = true)
	protected String custEmail;
	protected int mealid;
	protected int cabinid;
	protected int speRequestid;
	protected int flDetailid;
	protected List<Integer> planid;
	@XmlElement(required = true)
	protected String cfname;
	@XmlElement(required = true)
	protected String cmname;
	@XmlElement(required = true)
	protected String clname;
	@XmlElement(required = true)
	protected String cardnum;
	@XmlElement(required = true)
	protected String cardtype;
	@XmlElement(required = true)
	@XmlSchemaType(name = "date")
	protected Date cardExpiry;

	/**
	 * Gets the value of the custEmail property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCustEmail() {
		return custEmail;
	}

	/**
	 * Sets the value of the custEmail property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCustEmail(String value) {
		this.custEmail = value;
	}

	/**
	 * Gets the value of the mealid property.
	 * 
	 */
	public int getMealid() {
		return mealid;
	}

	/**
	 * Sets the value of the mealid property.
	 * 
	 */
	public void setMealid(int value) {
		this.mealid = value;
	}

	/**
	 * Gets the value of the cabinid property.
	 * 
	 */
	public int getCabinid() {
		return cabinid;
	}

	/**
	 * Sets the value of the cabinid property.
	 * 
	 */
	public void setCabinid(int value) {
		this.cabinid = value;
	}

	/**
	 * Gets the value of the speRequestid property.
	 * 
	 */
	public int getSpeRequestid() {
		return speRequestid;
	}

	/**
	 * Sets the value of the speRequestid property.
	 * 
	 */
	public void setSpeRequestid(int value) {
		this.speRequestid = value;
	}

	/**
	 * Gets the value of the flDetailid property.
	 * 
	 */
	public int getFlDetailid() {
		return flDetailid;
	}

	/**
	 * Sets the value of the flDetailid property.
	 * 
	 */
	public void setFlDetailid(int value) {
		this.flDetailid = value;
	}

	/**
	 * Gets the value of the cfname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCfname() {
		return cfname;
	}

	public List<Integer> getPlanid() {
		return planid;
	}

	public void setPlanid(List<Integer> planid) {
		this.planid = planid;
	}

	/**
	 * Sets the value of the cfname property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCfname(String value) {
		this.cfname = value;
	}

	/**
	 * Gets the value of the cmname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCmname() {
		return cmname;
	}

	/**
	 * Sets the value of the cmname property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCmname(String value) {
		this.cmname = value;
	}

	/**
	 * Gets the value of the clname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getClname() {
		return clname;
	}

	/**
	 * Sets the value of the clname property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setClname(String value) {
		this.clname = value;
	}

	/**
	 * Gets the value of the cardnum property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCardnum() {
		return cardnum;
	}

	/**
	 * Sets the value of the cardnum property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCardnum(String value) {
		this.cardnum = value;
	}

	/**
	 * Gets the value of the cardtype property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCardtype() {
		return cardtype;
	}

	/**
	 * Sets the value of the cardtype property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCardtype(String value) {
		this.cardtype = value;
	}

	/**
	 * Gets the value of the cardExpiry property.
	 * 
	 * @return possible object is {@link Date }
	 * 
	 */
	public Date getCardExpiry() {
		return cardExpiry;
	}

	/**
	 * Sets the value of the cardExpiry property.
	 * 
	 * @param value allowed object is {@link Date }
	 * 
	 */
	public void setCardExpiry(Date value) {
		this.cardExpiry = value;
	}

}
